# Generated by Django 2.1.3 on 2018-11-26 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='saliou/'),
            preserve_default=False,
        ),
    ]
