# Generated by Django 2.1.3 on 2018-11-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cours_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
