# Generated by Django 2.1.3 on 2018-11-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181126_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='image',
            field=models.ImageField(upload_to='saliou/'),
        ),
    ]
